credentials:
  usernames:
    luis:
      email: luis@email.com
      name: Luis Eduardo
      password: '$2b$12$y1xJr3U1kYJoRkzTKxd1ZODvG5q8vMBVbBoHfEgiRJmfMoM6NYRPu'  # senha: 1234

cookie:
  expiry_days: 30
  key: some_signature_key
  name: streamlit_login_cookie

preauthorized:
  emails:
    - luis@email.com